from __future__ import annotations

import re
from typing import Any

from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.helpers import device_registry as dr
from homeassistant.helpers import entity_registry as er
from homeassistant.helpers.aiohttp_client import async_get_clientsession

from .api import CatchSolarApiClient
from .const import (
    CONF_ENABLE_DAILY_ENERGY,
    CONF_ENABLE_LIVE_DATA,
    CONF_LOCATION_ID,
    CONF_PASSWORD,
    CONF_USERNAME,
    DEFAULT_ENABLE_DAILY_ENERGY,
    DEFAULT_ENABLE_LIVE_DATA,
    DOMAIN,
    PLATFORMS,
)
from .coordinator import CatchSolarDataUpdateCoordinator
from .entity import location_device_identifier, location_device_name
from .runtime import PrimaryLoadRuntimeTracker
from .runtime_data import CatchSolarConfigEntry, CatchSolarRuntimeData
from .telemetry import (
    CatchSolarDailyEnergyCoordinator,
    CatchSolarLiveClient,
    CatchSolarLiveCoordinator,
)

_REMOVED_ENTITY_UNIQUE_ID_TEMPLATES = (
    "{location_id}_solar_power",
    "{location_id}_total_consumption_power",
    "{location_id}_export_import_power",
    # Generated by the pre-cleanup live-channel parser in beta/dev builds.
    "{location_id}_channel_OTHER:undefined_live_power",
)
_RENAMED_ENTITY_UNIQUE_ID_TEMPLATES = (
    ("{location_id}_live_export_limit", "{location_id}_live_active_control"),
)
# Live sensor unique-id suffixes that are no longer produced, each appended to
# "{location_id}". "[^:]*" is an intentional regex class, so these are not
# escaped. Config-entry version 4 deletes the entities already created.
_RETIRED_LIVE_ENTITY_UNIQUE_ID_SUFFIXES = (
    # Channel power sensors built from a channel that carried only a type, e.g.
    # "8382_channel_MAINS:_live_power". Their generated entity name collided
    # with the site-level "Live Mains Power" sensor, leaving a `_2` duplicate.
    r"_channel_[^:]*:_live_power",
    # Actor power sensors. The upstream `pwr` field is not a usable measurement
    # for the relay actors this integration supports, so these read a permanent,
    # plausible-looking 0 W (e.g. "8382_actor_GLD.SR.3649_live_power").
    r"_actor_[^:]*_live_power",
)


def _async_register_location_device(
    hass: HomeAssistant,
    entry: CatchSolarConfigEntry,
    location: dict[str, Any],
) -> str | None:
    """Create the location device up-front and return its registry id.

    Registering the parent before the platforms are forwarded lets child
    devices reference it by id (``DeviceInfo["via_device_id"]``) rather than
    the deprecated ``via_device`` identifier tuple, and removes any dependency
    on entity creation order.
    """
    location_id = location.get("id")
    if location_id is None:
        return None
    device_entry = dr.async_get(hass).async_get_or_create(
        config_entry_id=entry.entry_id,
        identifiers={location_device_identifier(location_id)},
        manufacturer="CATCH Power",
        model="Monocle Location",
        name=location_device_name(location),
    )
    return device_entry.id


async def async_setup_entry(hass: HomeAssistant, entry: CatchSolarConfigEntry) -> bool:
    session = async_get_clientsession(hass)
    api = CatchSolarApiClient(
        session,
        entry.data[CONF_USERNAME],
        entry.data[CONF_PASSWORD],
    )
    runtime_tracker = PrimaryLoadRuntimeTracker(hass, entry.entry_id)
    await runtime_tracker.async_load()

    coordinator = CatchSolarDataUpdateCoordinator(
        hass,
        api,
        {**entry.data, **entry.options},
        runtime_tracker,
        config_entry=entry,
    )
    await coordinator.async_config_entry_first_refresh()
    coordinator.location_device_id = _async_register_location_device(
        hass,
        entry,
        coordinator.data.get("location") or {},
    )

    merged_config = {**entry.data, **entry.options}
    daily_energy_coordinator = None
    if merged_config.get(CONF_ENABLE_DAILY_ENERGY, DEFAULT_ENABLE_DAILY_ENERGY):
        daily_energy_coordinator = CatchSolarDailyEnergyCoordinator(hass, api, merged_config)
        await daily_energy_coordinator.async_refresh()

    live_coordinator = None
    live_client = None
    if merged_config.get(CONF_ENABLE_LIVE_DATA, DEFAULT_ENABLE_LIVE_DATA):
        live_coordinator = CatchSolarLiveCoordinator(hass, merged_config)
        live_coordinator.location_device_id = coordinator.location_device_id
        live_client = CatchSolarLiveClient(
            hass,
            api,
            session,
            int(merged_config[CONF_LOCATION_ID]),
            live_coordinator,
        )

    runtime_data = CatchSolarRuntimeData(
        coordinator=coordinator,
        runtime_tracker=runtime_tracker,
        daily_energy_coordinator=daily_energy_coordinator,
        live_coordinator=live_coordinator,
        live_client=live_client,
    )
    entry.runtime_data = runtime_data

    if live_client is not None:
        await live_client.async_start()

    try:
        await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
    except Exception:
        if live_client is not None:
            await live_client.async_stop()
        if daily_energy_coordinator is not None:
            await daily_energy_coordinator.async_shutdown()
        raise
    return True


async def async_unload_entry(hass: HomeAssistant, entry: CatchSolarConfigEntry) -> bool:
    runtime_data = entry.runtime_data
    if runtime_data is None:
        return True
    live_client = runtime_data.live_client
    daily_energy_coordinator = runtime_data.daily_energy_coordinator
    if live_client is not None:
        await live_client.async_stop()

    unload_ok = await hass.config_entries.async_unload_platforms(entry, PLATFORMS)
    if unload_ok:
        if daily_energy_coordinator is not None:
            await daily_energy_coordinator.async_shutdown()
    elif live_client is not None:
        await live_client.async_start()
    return unload_ok


async def async_remove_entry(hass: HomeAssistant, entry: CatchSolarConfigEntry) -> None:
    runtime_data = entry.runtime_data
    runtime_tracker = runtime_data.runtime_tracker if runtime_data is not None else None
    if runtime_tracker is None:
        runtime_tracker = PrimaryLoadRuntimeTracker(hass, entry.entry_id)
        await runtime_tracker.async_load()
    await runtime_tracker.async_delete()


async def async_remove_config_entry_device(
    hass: HomeAssistant, entry: CatchSolarConfigEntry, device_entry: dr.DeviceEntry
) -> bool:
    """Allow registry deletion only after Catch no longer reports the device."""
    runtime_data = entry.runtime_data
    if runtime_data is None:
        return False

    known_identifiers: set[tuple[str, str]] = set()
    core_data = runtime_data.coordinator.data or {}
    location_id = (core_data.get("location") or {}).get("id")
    if location_id is not None:
        known_identifiers.add((DOMAIN, f"location_{location_id}"))
    for device in core_data.get("devices", []):
        device_id = device.get("id")
        if device_id is not None:
            known_identifiers.add((DOMAIN, f"device_{device_id}"))

    live_data = runtime_data.live_coordinator.data if runtime_data.live_coordinator else {}
    for actor in live_data.get("actors", []):
        actor_id = actor.get("id")
        if actor_id is not None and location_id is not None:
            known_identifiers.add((DOMAIN, f"location_{location_id}_actor_{actor_id}"))

    return not any(identifier in known_identifiers for identifier in device_entry.identifiers)


def _remove_retired_live_entities(hass: HomeAssistant, location_id: object) -> int:
    """Delete live sensors this integration no longer produces."""
    registry = er.async_get(hass)
    prefix = re.escape(str(location_id))
    patterns = [
        re.compile("^" + prefix + suffix + "$")
        for suffix in _RETIRED_LIVE_ENTITY_UNIQUE_ID_SUFFIXES
    ]
    removed = 0
    for entity_entry in list(registry.entities.values()):
        if entity_entry.platform != DOMAIN or entity_entry.domain != "sensor":
            continue
        unique_id = entity_entry.unique_id or ""
        if any(pattern.match(unique_id) for pattern in patterns):
            registry.async_remove(entity_entry.entity_id)
            removed += 1
    return removed


async def async_migrate_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Remove retired entities and migrate the active-control sensor name."""
    if entry.version >= 4:
        return True

    options = dict(entry.options)
    location_id = entry.data.get(CONF_LOCATION_ID)

    if entry.version < 3:
        options.pop("enable_power_data", None)
        if location_id is not None:
            registry = er.async_get(hass)
            for unique_id_template in _REMOVED_ENTITY_UNIQUE_ID_TEMPLATES:
                entity_id = registry.async_get_entity_id(
                    "sensor",
                    DOMAIN,
                    unique_id_template.format(location_id=location_id),
                )
                if entity_id is not None:
                    registry.async_remove(entity_id)
            for old_template, new_template in _RENAMED_ENTITY_UNIQUE_ID_TEMPLATES:
                entity_id = registry.async_get_entity_id(
                    "sensor",
                    DOMAIN,
                    old_template.format(location_id=location_id),
                )
                if entity_id is not None:
                    registry.async_update_entity(
                        entity_id,
                        new_unique_id=new_template.format(location_id=location_id),
                    )

    if entry.version < 4 and location_id is not None:
        _remove_retired_live_entities(hass, location_id)

    hass.config_entries.async_update_entry(entry, options=options, version=4)
    return True


async def async_setup(hass: HomeAssistant, config: dict) -> bool:
    """Set up the Catch Solar component from configuration.yaml.

    This integration is configured exclusively through the config flow (UI).
    YAML-based setup is not supported — this stub exists so Home Assistant
    does not log a warning about a missing setup function.
    """
    return True
