from __future__ import annotations

from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.helpers import device_registry as dr
from homeassistant.helpers import entity_registry as er
from homeassistant.helpers.aiohttp_client import async_get_clientsession

from .api import CatchSolarApiClient
from .const import (
    CONF_ENABLE_DAILY_ENERGY,
    CONF_ENABLE_LIVE_DATA,
    CONF_LOCATION_ID,
    CONF_PASSWORD,
    CONF_USERNAME,
    DEFAULT_ENABLE_DAILY_ENERGY,
    DEFAULT_ENABLE_LIVE_DATA,
    DOMAIN,
    PLATFORMS,
)
from .coordinator import CatchSolarDataUpdateCoordinator
from .runtime import PrimaryLoadRuntimeTracker
from .runtime_data import CatchSolarConfigEntry, CatchSolarRuntimeData
from .telemetry import (
    CatchSolarDailyEnergyCoordinator,
    CatchSolarLiveClient,
    CatchSolarLiveCoordinator,
)

_REMOVED_ENTITY_UNIQUE_ID_TEMPLATES = (
    "{location_id}_solar_power",
    "{location_id}_total_consumption_power",
    "{location_id}_export_import_power",
    # Generated by the pre-cleanup live-channel parser in beta/dev builds.
    "{location_id}_channel_OTHER:undefined_live_power",
)
_RENAMED_ENTITY_UNIQUE_ID_TEMPLATES = (
    ("{location_id}_live_export_limit", "{location_id}_live_active_control"),
)


async def async_setup_entry(hass: HomeAssistant, entry: CatchSolarConfigEntry) -> bool:
    session = async_get_clientsession(hass)
    api = CatchSolarApiClient(
        session,
        entry.data[CONF_USERNAME],
        entry.data[CONF_PASSWORD],
    )
    runtime_tracker = PrimaryLoadRuntimeTracker(hass, entry.entry_id)
    await runtime_tracker.async_load()

    coordinator = CatchSolarDataUpdateCoordinator(
        hass,
        api,
        {**entry.data, **entry.options},
        runtime_tracker,
        config_entry=entry,
    )
    await coordinator.async_config_entry_first_refresh()

    merged_config = {**entry.data, **entry.options}
    daily_energy_coordinator = None
    if merged_config.get(CONF_ENABLE_DAILY_ENERGY, DEFAULT_ENABLE_DAILY_ENERGY):
        daily_energy_coordinator = CatchSolarDailyEnergyCoordinator(hass, api, merged_config)
        await daily_energy_coordinator.async_refresh()

    live_coordinator = None
    live_client = None
    if merged_config.get(CONF_ENABLE_LIVE_DATA, DEFAULT_ENABLE_LIVE_DATA):
        live_coordinator = CatchSolarLiveCoordinator(hass, merged_config)
        live_client = CatchSolarLiveClient(
            hass,
            api,
            session,
            int(merged_config[CONF_LOCATION_ID]),
            live_coordinator,
        )

    runtime_data = CatchSolarRuntimeData(
        coordinator=coordinator,
        runtime_tracker=runtime_tracker,
        daily_energy_coordinator=daily_energy_coordinator,
        live_coordinator=live_coordinator,
        live_client=live_client,
    )
    entry.runtime_data = runtime_data

    if live_client is not None:
        await live_client.async_start()

    try:
        await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
    except Exception:
        if live_client is not None:
            await live_client.async_stop()
        if daily_energy_coordinator is not None:
            await daily_energy_coordinator.async_shutdown()
        raise
    return True


async def async_unload_entry(hass: HomeAssistant, entry: CatchSolarConfigEntry) -> bool:
    runtime_data = entry.runtime_data
    if runtime_data is None:
        return True
    live_client = runtime_data.live_client
    daily_energy_coordinator = runtime_data.daily_energy_coordinator
    if live_client is not None:
        await live_client.async_stop()

    unload_ok = await hass.config_entries.async_unload_platforms(entry, PLATFORMS)
    if unload_ok:
        if daily_energy_coordinator is not None:
            await daily_energy_coordinator.async_shutdown()
    elif live_client is not None:
        await live_client.async_start()
    return unload_ok


async def async_remove_entry(hass: HomeAssistant, entry: CatchSolarConfigEntry) -> None:
    runtime_data = entry.runtime_data
    runtime_tracker = runtime_data.runtime_tracker if runtime_data is not None else None
    if runtime_tracker is None:
        runtime_tracker = PrimaryLoadRuntimeTracker(hass, entry.entry_id)
        await runtime_tracker.async_load()
    await runtime_tracker.async_delete()


async def async_remove_config_entry_device(
    hass: HomeAssistant, entry: CatchSolarConfigEntry, device_entry: dr.DeviceEntry
) -> bool:
    """Allow registry deletion only after Catch no longer reports the device."""
    runtime_data = entry.runtime_data
    if runtime_data is None:
        return False

    known_identifiers: set[tuple[str, str]] = set()
    core_data = runtime_data.coordinator.data or {}
    location_id = (core_data.get("location") or {}).get("id")
    if location_id is not None:
        known_identifiers.add((DOMAIN, f"location_{location_id}"))
    for device in core_data.get("devices", []):
        device_id = device.get("id")
        if device_id is not None:
            known_identifiers.add((DOMAIN, f"device_{device_id}"))

    live_data = runtime_data.live_coordinator.data if runtime_data.live_coordinator else {}
    for actor in live_data.get("actors", []):
        actor_id = actor.get("id")
        if actor_id is not None and location_id is not None:
            known_identifiers.add((DOMAIN, f"location_{location_id}_actor_{actor_id}"))

    return not any(identifier in known_identifiers for identifier in device_entry.identifiers)


async def async_migrate_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Remove retired entities and migrate the active-control sensor name."""
    if entry.version >= 3:
        return True

    options = dict(entry.options)
    options.pop("enable_power_data", None)

    location_id = entry.data.get(CONF_LOCATION_ID)
    if location_id is not None:
        registry = er.async_get(hass)
        for unique_id_template in _REMOVED_ENTITY_UNIQUE_ID_TEMPLATES:
            entity_id = registry.async_get_entity_id(
                "sensor",
                DOMAIN,
                unique_id_template.format(location_id=location_id),
            )
            if entity_id is not None:
                registry.async_remove(entity_id)
        for old_template, new_template in _RENAMED_ENTITY_UNIQUE_ID_TEMPLATES:
            entity_id = registry.async_get_entity_id(
                "sensor",
                DOMAIN,
                old_template.format(location_id=location_id),
            )
            if entity_id is not None:
                registry.async_update_entity(
                    entity_id,
                    new_unique_id=new_template.format(location_id=location_id),
                )

    hass.config_entries.async_update_entry(entry, options=options, version=3)
    return True


async def async_setup(hass: HomeAssistant, config: dict) -> bool:
    """Set up the Catch Solar component from configuration.yaml.

    This integration is configured exclusively through the config flow (UI).
    YAML-based setup is not supported — this stub exists so Home Assistant
    does not log a warning about a missing setup function.
    """
    return True
